# _config.yml

remote_theme             : "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin    : "dark"


title                    : "Md Belal Hossain Santo"
subtitle                 : "Aspiring Data Scientist | Software Engineer"
name                     : "Your Name"
description              : "Junior Data Scientist passionate about transforming data into actionable insights"
url                      : "https://bhsanto.github.io"
baseurl                  : ""
repository               : "bhsanto/bhsanto.github.io"
