# _config.yml
logo: /assets/profile-pic.jpg
title: Md Belal Hossain Santo | Software Engineering Grad | Data Science Aspirant
description: Passionate about software and data science
author: Md Belal Hossain Santo
email: bhsanto786@gmail.com

# Theme settings
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to use the remote theme

# Repository settings
repository: bhsanto/bhsanto.github.io

# Footer content
footer_content: "© 2025 Md Belal Hossain Santo. All rights reserved."

# Show downloads
show_downloads: false
